# Generated by Django 3.1.7 on 2021-05-25 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0006_auto_20210507_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership_end',
        ),
        migrations.RemoveField(
            model_name='member',
            name='staff_assigned',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='access_key_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.bank'),
        ),
        migrations.AddField(
            model_name='member',
            name='card_expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='card_holder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='card_type',
            field=models.CharField(blank=True, choices=[('M', 'Mastercard'), ('V', 'Visa')], max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_term',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='member',
            name='sales_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.salesperson'),
        ),
        migrations.CreateModel(
            name='MemberMembershipLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('membership_start', models.DateField()),
                ('membership_term', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membermembershiplog_created_by', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membership')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membermembershiplog_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('membership', 'member', 'membership_start')},
            },
        ),
    ]
