# Generated by Django 3.1.7 on 2021-05-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='packageproduct',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='branch',
        ),
    ]
